// `.env.json` is generated by the `npm run build` command
import * as env from './.env.json';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: 'http://localhost/',
  defaultLanguage: 'es-ES',
  supportedLanguages: [
    'en-US',
    'es-ES'
  ]
};
